In [1]:
import numpy as np

In [2]:
a = np.arange(1, 7)
a

array([1, 2, 3, 4, 5, 6])

In [3]:
np.save('my_array_a', a)

In [4]:
b = np.load('my_array_a.npy')
b

array([1, 2, 3, 4, 5, 6])

In [5]:
np.savetxt('my_array_a.txt', a)

In [6]:
b = np.loadtxt('my_array_a.txt')
b

array([1., 2., 3., 4., 5., 6.])

In [7]:
np.savetxt('my_array_a.csv', a)

In [8]:
b = np.loadtxt('my_array_a.csv')
b

array([1., 2., 3., 4., 5., 6.])

In [9]:
import pandas as pd

x = pd.read_csv('music.csv', header=0).values
print(x)
print(type(x))

[['Billie Holiday' 'Jazz' '1,300,000' '27,000,000']
 ['Jimmi Hendrix' 'Rock' '2,700,000' '70,000,000']
 ['Miles Davis' 'Jazz' '1,500,000' '48,000,000']
 ['SIA' 'Pop' '2,000,000' '74,000,000']]
<class 'numpy.ndarray'>


In [10]:
x = pd.read_csv('music.csv', usecols=['Artist', 'Plays']).values
print(x)

[['Billie Holiday' '27,000,000']
 ['Jimmi Hendrix' '70,000,000']
 ['Miles Davis' '48,000,000']
 ['SIA' '74,000,000']]


In [11]:
a = np.array([[-2.58289208,  0.43014843, -1.24082018, 1.59572603],
              [ 0.99027828, 1.17150989,  0.94125714, -0.14692469],
              [ 0.76989341,  0.81299683, -0.95068423, 0.11769564],
              [ 0.20484034,  0.34784527,  1.96979195, 0.51992837]])

In [12]:
df = pd.DataFrame(a)
print(df)

          0         1         2         3
0 -2.582892  0.430148 -1.240820  1.595726
1  0.990278  1.171510  0.941257 -0.146925
2  0.769893  0.812997 -0.950684  0.117696
3  0.204840  0.347845  1.969792  0.519928


In [13]:
df.to_csv('pd_df.csv')

In [14]:
data = pd.read_csv('pd_df.csv')

In [15]:
data

Unnamed: 0         0         1         2         3
0           0 -2.582892  0.430148 -1.240820  1.595726
1           1  0.990278  1.171510  0.941257 -0.146925
2           2  0.769893  0.812997 -0.950684  0.117696
3           3  0.204840  0.347845  1.969792  0.519928