In [1]:
import numpy as np

In [3]:
L = np.random.random(100)

In [4]:
sum(L)

49.522897260641216

In [5]:
np.sum(L)

49.522897260641216

In [7]:
big_array = np.random.rand(1_000_000)
%timeit sum(big_array)
%timeit np.sum(big_array)

60.6 ms ± 895 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
419 µs ± 3.77 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [9]:
min(big_array), max(big_array)

(1.55204143537091e-06, 0.9999999262620659)

In [10]:
np.min(big_array), np.max(big_array)

(1.55204143537091e-06, 0.9999999262620659)

In [11]:
%timeit min(big_array)
%timeit np.min(big_array)

47.9 ms ± 1.63 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
410 µs ± 6.62 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [12]:
print(big_array.min(), big_array.max(), big_array.sum())

1.55204143537091e-06 0.9999999262620659 499954.74367077055


In [13]:
M = np.random.rand(3, 4)
print(M)

[[0.68918225 0.3742367  0.12623328 0.19185652]
 [0.16504586 0.17926094 0.12099926 0.21117815]
 [0.94143516 0.30523242 0.19176216 0.20034818]]


In [15]:
M.sum()

3.6967708673877917

In [16]:
M.min()

0.12099925981588544

In [17]:
M.min(axis=0)

array([0.16504586, 0.17926094, 0.12099926, 0.19185652])

In [18]:
M.min(axis=1)

array([0.12623328, 0.12099926, 0.19176216])